name             'bb_elasticsearch'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures bb-elasticsearch'
long_description 'Installs/Configures bb-elasticsearch'
version          '0.1.0'

depends 'elasticsearch'
depends 'java'
