name             'namp_nfs'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures NFS'
long_description 'Installs/Configures Installs/Configures NFS for ES backups'
version          '0.1.0'
