ruby_block "Add AWS Billing Filters for Logstash" do 
	block do
		code[] = ""
		code << "input {"
		code << "  tcp {"
		code << "    port => 5140"
		code << "    codec => \"line\""
		code << "  }"
		code << "}"
		code << ""
		code << "filter {"
		code << "  json {"
		code << "    source => \"message\""
		code << "  }"
		code << ""
		code << "  mutate {"
		code << "    add_field => { \"index\" => \"logstash-%{+YYYY.MM.dd}\" }"
		code << "  }"
		code << ""
		code << "  if [type] == \"aws_billing_hourly\" or [type] == \"aws_billing_monthly\" {"
		code << "    if [type] == \"aws_billing_hourly\" {"
		code << "      date {"
		code << "        match => [ \"UsageStartDate\", \"ISO8601\" ]"
		code << "      }"
		code << "    }"
		code << "    if [type] == \"aws_billing_monthly\" {"
		code << "      date {"
		code << "        match => [ \"BillingPeriodStartDate\", \"ISO8601\" ]"
		code << "      }"
		code << "    }"
		code << "    mutate {"
		code << "      replace => [ \"index\", \"aws-billing-%{+YYYY.MM}\"]"
		code << "      remove_field => [ \"message\" ]"
		code << "    }"
		code << "  }"
		code << ""
		code << "}"
		code << ""
		code << "output {"
		code << "  elasticsearch {"
		code << "    embedded => true"
		code << "    index => \"%{index}\""
		code << "  }"
		code << "}"
		code.join("\n")
		ruby -pe 'puts code if $_ =~ /output/' < /etc/logstash/conf.d/server.conf
	end
	action: run
end