name             'bb_monitor'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures bb-monitor'
long_description 'Installs/Configures bb-monitor'
version          '0.1.0'

depends 'kibana'
depends 'htpasswd'
depends 'graphite'
depends 'python'
depends 'runit'
depends 'grafana'
depends 'sensu'
depends 'uchiwa'
depends 'nodejs'
