name             'bb_monitor'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures bb-monitor'
long_description 'Installs/Configures bb-monitor'
version          '0.1.0'

depends 'bb_external'
depends 'bb_elasticsearch'
depends 'grafana'
depends 'graphite'
depends 'htpasswd'
depends 'java'
depends 'simple-kibana'
depends 'nodejs'
depends 'python'
depends 'route53'
depends 'runit'
depends 'sensu'
depends 'uchiwa'
depends 'statsd'
